# Standard Libraries
from datetime import datetime

# Retrieval-Augmented Generation (RAG) Engine
from rag_engine import RetrievalAugmentedGenerationEngine

# Streamlit User Interface
import streamlit as st

class ArtificialIntelligenceMedicalChatbot:
    MODEL_OPTIONS = {"GPT-4o": "gpt-4o", "GPT-4o Mini": "gpt-4o-mini"}
    
    def __init__(self) -> None:
        self.intialise_dashboard()
        
    def intialise_dashboard(self) -> None:
        # Configure Page Settings
        st.set_page_config(page_title = "Artificial Intelligence Medical Chatbot", page_icon = "🩺", layout = "wide", initial_sidebar_state = "expanded")
        
        # Initialise Customs CSS
        st.markdown(
            """
            <style>
                .main { padding: 2rem; }
                
                .stChatMessage { padding: 1rem; border-radius: 0.5rem; margin-bottom: 1rem; }
                
                .disclaimer { background-color: #696969; border-left: 4px solid #474747; padding: 1rem; border-radius: 0.25rem; margin: 1rem 0; }
                
                .metric-container { background-color: #f8f9fa; padding: 1rem; border-radius: 0.5rem; border: 1px solid #dee2e6; }
            </style>
            """, unsafe_allow_html = True)
        
        #  Initialise Session State Variables
        if "messages" not in st.session_state:
            st.session_state.messages = []
        
        if "rag_engine" not in st.session_state:
            st.session_state.rag_engine = None
        
        if "model_name" not in st.session_state:
            st.session_state.model_name = "gpt-4o-mini"
            
        if "model_display_name" not in st.session_state:
            st.session_state.model_display_name = "GPT-4o Mini"
        
        if "k_documents" not in st.session_state:
            st.session_state.k_documents = 3
            
    @staticmethod
    @st.cache_resource
    def initialise_rag_engine(model_name: str) -> RetrievalAugmentedGenerationEngine:
        try:
            engine = RetrievalAugmentedGenerationEngine(large_language_model_name = model_name)
        
            return engine
        
        except Exception as e:
            st.error(f"Error Initialising RAG Engine: {str(e)}")
            return None
    
    def render_sidebar(self) -> tuple:
        with st.sidebar:
           # Information Section
            st.header("How Medical Chatbot Works")
            st.caption("This Artificial Intelligence Medical Chatbot uses Retrieval-Augmented Generation (RAG) to provide information based on medical documents. Following with combining the power of vector search and Large Language Models (LLMs).")
            
            st.divider() 
            
            st.header("Chatbot Settings")
            
            # Large Language Model
            st.text("Large Language Model")
            selected_model = st.selectbox("Select Model", options = list(self.MODEL_OPTIONS.keys()), index = list(self.MODEL_OPTIONS.keys()).index(st.session_state.model_display_name), help = "Choose a model for generating responses.")
        
            st.divider()
        
            # Retrieval Settings
            st.text("Retrieval Setting")
            k_documents = st.slider("Number of Documents to Retrieve", min_value = 1, max_value = 10, value = st.session_state.k_documents, help = "More documents provide more context but may increase response time")
            
            st.divider()
            
            # Clear History
            if st.button("Clear Chat History", use_container_width = True):
                st.session_state.messages = []
                st.rerun()
            
        return self.MODEL_OPTIONS[selected_model], selected_model, k_documents
            
    def render_header(self) -> None:
        st.title("Medical Chatbot")
        st.caption("Powered by OpenAI and LangChain")
        
        st.markdown("""
        <div class="disclaimer">
            <strong>Medical Disclaimer:</strong> The information provided by this chatbot is for general informational purposes only and should not be considered a replacement for professional medical advice. Please consult a 
            qualified healthcare professional for diagnosis, treatment, or any medical-related concerns.
        </div>
        """, unsafe_allow_html = True)
        
    def render_chat_history(self) -> None:
        for message in st.session_state.messages:
            with st.chat_message(message["role"]):
                st.markdown(message["content"], unsafe_allow_html = True)
                
                if message["role"] == "assistant":
                    st.caption("Generated by AI Medical Chatbot")
    
    def render_metrics(self, model_name: str, k_documents: int) -> None:
        st.divider()
        col1, col2, col3 = st.columns(3)
        
        with col1:
            st.metric("Messages", len(st.session_state.messages))
        
        with col2:
            st.metric("Current Used Model", model_name)
        
        with col3:
            st.metric("Documents Retrieved", k_documents)

    def process_user_input(self, prompt: str, rag_engine: RetrievalAugmentedGenerationEngine) -> None:
        # Display user message
        st.session_state.messages.append({"role": "user", "content": prompt})
        
        with st.chat_message("user"):
            st.markdown(prompt)
        
        # Generate response
        with st.chat_message("assistant"):
            with st.spinner("Thinking"):
                try:
                    response = rag_engine.answer_query(prompt)
                    answer = response["answer"]
                    
                    st.markdown(answer)
                    
                    # Show Source Documents
                    if "context" in response and response["context"]:
                        with st.expander("Source Documents"):
                            for idx, doc in enumerate(response["context"], 1):
                                st.text(f"Source {idx}:")
                                st.caption(doc.page_content[:450] + "...")
                                # st.markdown(f"<div style='text-align: justify; white-space: pre-wrap;'>{doc.page_content[:450]}...</div>", unsafe_allow_html = True, width = "content")
                                
                                if hasattr(doc, 'metadata') and doc.metadata:
                                    st.caption(f"Metadata: {doc.metadata}")
                                
                                st.divider()
                    
                    st.caption("Generated by AI Medical Chatbot")
                    
                    st.session_state.messages.append({"role": "assistant", "content": answer})
                    
                except Exception as e:
                    error_message = f"Sorry, I encountered an error: {str(e)}"
                    st.error(error_message)
                    st.session_state.messages.append({"role": "assistant", "content": error_message})
    
    def launch(self) -> None:
        # Sidebar - Settings & Information
        model_name, model_display_name, k_documents = self.render_sidebar()
        
        # Main Page - Header
        self.render_header()

        # Initialise or Update RAG Engine
        if (st.session_state.rag_engine is None or st.session_state.model_name != model_name):
            with st.spinner("Loading medical knowledge base..."):
                st.session_state.rag_engine = self.initialise_rag_engine(model_name)
                st.session_state.model_name = model_name
                st.session_state.model_display_name = model_display_name
                
                if st.session_state.rag_engine:
                    # Build RAG Chain with Current k Value
                    st.session_state.rag_engine.build_rag_chain(k = k_documents)
                    st.session_state.k_documents = k_documents
        
        # Update k Value if User Changed
        if st.session_state.k_documents != k_documents:
            st.session_state.rag_engine.build_rag_chain(k = k_documents)
            st.session_state.k_documents = k_documents
        
        # Check if RAG engine is Initialised
        if st.session_state.rag_engine is None:
            st.error("Failed to initialise the chatbot. Please check your configuration and try again.")
            st.stop()
        
        # Main Page - Chat History
        self.render_chat_history()
        
        # Main Page - Chat Input
        if prompt := st.chat_input("Describe the symptoms you are experiencing"):
            self.process_user_input(prompt, st.session_state.rag_engine)
        
        # Main Page - Metrics Footer
        self.render_metrics(model_display_name, k_documents)

# === Launch Dashboard ===
if __name__ == "__main__":
    app = ArtificialIntelligenceMedicalChatbot()
    app.launch()